spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8889

server:
  port: 9090   # API Gateway port

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/books/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
    compatibility-verifier:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server port (must be different)
    register-with-eureka: true
    fetch-registry: true

